### ISSUE TITLE
Small typo in makefile io

### ISSUE THREAD

**Issue by paullunk** [flatironinstitute/FMM3D#21]
Hi everybody,

I have compiled the library myself for the first time this week. Great work!

I am not sure, not a native English speaker, but I think this information to the user about the use of the makefile:

https://github.com/flatironinstitute/FMM3D/blob/e42473a8091d33a83cbdb631cff4660ce7f94a96/makefile#L177

should say something like:

"...for using vectorized kernel and multi-threaded evaluation"
"...for using vectorized kernel evaluation and multi-threading"

Best regards from Germany,
Paul

**Comment by askhamwhat** [comment]
Fixed by 7ba20d6bfefeca9e2e6675411a3249b6b832b1f6

**Comment by askhamwhat** [comment]
Thank you, @paullunk for pointing it out
