### ISSUE TITLE
Wheel for python 3.9

### ISSUE THREAD

**Issue by GuillaumeQuenneville** [flatironinstitute/FMM3D#23]
Would it be possible to publish a wheel for python 3.9? at the moment it errors out with

ERROR: Could not find a version that satisfies the requirement fmm3dpy (from versions: none)

when trying to pip install.

Thank you

**Comment by lu1and10** [comment]
Hi,

We uploaded some new version fmm3dpy wheels, [python wheels](https://pypi.org/project/fmm3dpy/#files)
