### ISSUE TITLE
stack size linker options on MacOS 

### ISSUE THREAD

**Issue by oneilm** [flatironinstitute/FMM3D#4]
For larger multicore problems, my experience has been that the stack size needs to be set as a linker option on MacOS (since the stack size cannot be set to unlimited in the terminal on MacOS). For example, with the flag:

-Wl,-stack_size,0x40000000

This requires changing the macos .inc file, or adding an LDFLAGS variable. Or is this not necessary using the current make file configuration?

**Comment by mrachh** [comment]
Hi Mike,
This is not necessary, as there is very little statically allocated memory in the code.
