### ISSUE TITLE
Adding the Julia wrapper to the official registry of Julia packages

### ISSUE THREAD

**Issue by maltezfaria** [flatironinstitute/FMM3D#44]
Hi,

First of all, thanks for developing and maintaining this library -- I have found it to be very useful!

For the Julia wrapper, I was wondering if it would be possible to register the *module* as an official Julia package, so that:
1. Other registered packages can (officially) depend on it
2. People can use the julia built-in package manager to add and version-control the `FMM3D.jl` module (e.g. `]add FMM3D`)

I have never registered a package that lives in a subdirectory, but from the [Registrator docs](https://juliapackages.com/p/registrator) it seems to be as easy as writing
```
@JuliaRegistrator register subdir=path/to/my/package
```
on the commit. 

Thanks!

**Comment by mipals** [comment]
I support this suggestion!

**Comment by lu1and10** [comment]
I installed the Registrator bot and I tried to comment on the latest commit a few times. Seems not working for me, @askhamwhat do you know how to trigger the registrator?

**Comment by maltezfaria** [comment]
Thanks for giving this a try! It seems that the bot was not triggered by your message (not sure why). Perhaps something is wrong with the installation of the bot? 

Alternatively, you can try using the web interface to register the package: https://juliahub.com/ui/Packages

**Comment by lu1and10** [comment]
> Thanks for giving this a try! It seems that the bot was not triggered by your message (not sure why). Perhaps something is wrong with the installation of the bot?
> 
> Alternatively, you can try using the web interface to register the package: https://juliahub.com/ui/Packages

Thanks for looking into this!
It seems that either installing the julia registrator bot to FMM3D repo or using the web interface needs some access privilege of the flatironinstitute organization github account since the repo is under the organization.
My account does not have the access to do that, I've contacted the flatironinstitute organization github account admin to ask them adding the julia registrator bot to the repo, after adding the bot app we can try to trigger the bot.

**Comment by ahbarnett** [comment]
Would this be solved by making a separate FMM3D.jl repo, as is standard for Julia packages? (eg see FINUFFT.jl).   I would love to use this.

**Comment by mipals** [comment]
Pretty sure that i will not change anything @ahbarnett . The thing blocking this ended up being some license issue and the name being auto flagged as too close to the already registered FMM2D. [The discussion is here, and it actually looks like it got merged into the registry yesterday. ](https://github.com/JuliaRegistries/General/pull/98072). Although I do not know what *temporarily deployed to stopwatch* means.

**Comment by mipals** [comment]
I've contacted some of the people in charge of package registration. It seems like the registration is blocked due to the license not being in the Julia subfolder. Would it possible to add a copy of the license to subfolder?

**Comment by mipals** [comment]
A quick update: The license that is missing is actually for the Julia code in said subfolder. The license for the library is distributed in FMM3D_jll package. Sorry for the confusion.

**Comment by mrachh** [comment]
Sorry about the delay, we were waiting to clear up some licensing stuff, it should be in the Julia folder now.

**Comment by mipals** [comment]
No stress. I will try to ping some of the Julia registry people - Hopefully this means that FMM3D can be registered soon 🥳 

I just noticed that the Julia wrapper refers to a version 1.0.1, while the current version of FMM3D seem to be 1.0.4. If you want I can try to see if I can get some new binaries built.

**Comment by maltezfaria** [comment]
Thanks @mipals, @mrachh, and @lu1and10 for your work in getting `FMM3D.jl` registered! 

I saw one last conflict blocking the auto-merge in the Julia General Registry, but someone on the Julia side with merge rights can hopefully take over now and merge the registration PR.
