### ISSUE TITLE
make lib fails on macOS

### ISSUE THREAD

**Issue by oneilm** [flatironinstitute/FMM3D#5]
With the following in make.inc:
- - - - 
CC=gcc-9
CXX=g++-9
FC=gfortran-9
CFLAGS += -I src 

# OpenMP with gcc on OSX needs the following
OMPFLAGS = -fopenmp
OMPLIBS = -lgomp 
- - - - 

Running "make lib" fails with many errors, the first of which is:
- - - - 
Undefined symbols for architecture x86_64:
  "std::ctype<char>::_M_widen_init() const", referenced from:
      sctl::SphericalHarmonics<double>::WriteVTK(char const*, sctl::Vector<double> const*, sctl::Vector<double> const*, sctl::SHCArrange, long long, long long, double, sctl::Comm const&) in libkernels.o
...
- - - -

**Comment by lu1and10** [comment]
Hi Mike,

Thanks for pointing this out. We now use Dhairya's SCTL C++ library which need to link with stdc++ lib for dynamic lib, in makefile, if you change "LIBS = -lm" to "LIBS = -lm -lstdc++" in makefile, it may work.

Best,
Libin

**Comment by oneilm** [comment]
Yes that worked.

- -
Mike O’Neil
www.cims.nyu.edu/~oneil
oneil@cims.nyu.edu
212-998-3125

**Comment by lu1and10** [comment]
> Yes that worked. - - Mike O’Neil [www.cims.nyu.edu/~oneil](http://www.cims.nyu.edu/~oneil) oneil@cims.nyu.edu 212-998-3125
> […](#)

Glad it works. Sorry about that, we will fix this in the next commit.

**Comment by lu1and10** [comment]
added  -lstdc++ flag in makefile.
