### ISSUE TITLE
Register the Julia version as a stand alone package

### ISSUE THREAD

**Issue by ArrogantGao** [flatironinstitute/FMM3D#57]
Hi, I am a Julia user and I wonder do you have the plan to register the Julia version as a stand alone package? 
Julia community provides a set of tools for registering (see https://github.com/JuliaRegistries/General), after registering, other Julia user can directly download the package using the package management tool in Julia (similar to `pip`) to install the package, and they will be able to use FMM.jl to develop their own package more easily.

I can help if you are interested about that.

**Comment by lu1and10** [comment]
> Hi, I am a Julia user and I wonder do you have the plan to register the Julia version as a stand alone package? Julia community provides a set of tools for registering (see https://github.com/JuliaRegistries/General), after registering, other Julia user can directly download the package using the package management tool in Julia (similar to `pip`) to install the package, and they will be able to use FMM.jl to develop their own package more easily.
> 
> I can help if you are interested about that.

Yes, thanks for the help. We are interested in registering for Julia.
I thought we tried a few months ago(https://github.com/JuliaRegistries/General/tree/master/F/FMM3D).
Could you help to verify it's not working? If so, it will be appreciated to help us make it work.

**Comment by ArrogantGao** [comment]
Thanks a lot for your help, I thought I was not registered since I does not seems like a standard Julia package.
It works correctly, thanks!

**Comment by ArrogantGao** [comment]
I submit a PR #58 to update the readme of the Julia version.
